#!/bin/bash
# Run all test scripts in sequence
# This is the equivalent of the old autotests.sh - runs all thematic test suites
# Creates a single Neon branch and reuses it for all test groups
#
# Usage:
#   ./autotestsall.sh [--no-neon]
#
# Optimization strategy:
# 1. Run tests in dependency order (unit → integration → database → optimization)
# 2. Use shared DATABASE_URL to avoid multiple Neon branch creations
# 3. Sequential execution for database tests (prevents race conditions)
# 4. Parallel execution where safe (unit tests, non-database integration tests)
# 5. Let Cargo handle incremental compilation automatically (no pre-compilation)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Scripts are in root, so stay in the rust directory
cd "$SCRIPT_DIR" || exit 1

# Source common setup for Neon branch management
source "$SCRIPT_DIR/common_setup.sh"

# Parse flags
USE_NEON=true
for arg in "$@"; do
    case "$arg" in
        --no-neon)
            USE_NEON=false
            ;;
        *)
            echo "Unknown flag: $arg" >&2
            echo "Usage: $0 [--no-neon]" >&2
            exit 1
            ;;
    esac
done

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Running full test suite (all scripts)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create a single Neon branch for all tests (if requested)
if [ "$USE_NEON" = true ]; then
    trap cleanup_neon_branch EXIT
    setup_neon_branch
    # Export DATABASE_URL so child scripts will skip branch creation
    export DATABASE_URL
    export EPHEMERAL_DB=1
    echo "✅ Using shared Neon branch for all test groups: $BRANCH_NAME"
    echo ""
elif [ -z "${DATABASE_URL:-}" ]; then
    echo "⚠️  DATABASE_URL not set and --no-neon specified" >&2
    exit 1
fi

# Match CI behavior: Don't set RUN_HEAVY_TESTS (CI doesn't set it, so heavy tests are skipped)
# This ensures autotestsall.sh is a true predictor of CI test success
# If you want to run heavy tests locally, set RUN_HEAVY_TESTS=true before running this script
# or use individual test scripts which set RUN_HEAVY_TESTS=true by default
unset RUN_HEAVY_TESTS
export CI="true"  # Match CI environment

# Clean corrupted artifacts that can cause compilation errors and WSL crashes
# This prevents "Archive member size is too large", type inference errors, and corrupt incremental artifacts
# ROOT CAUSE: WSL crashes corrupt incremental compilation artifacts (dep-graph.bin files)
# These corrupt files accumulate and cause resource exhaustion when cargo processes them
# Solution: Proactively clean corrupt files before they accumulate
if [ -d "target" ]; then
    echo "🧹 Cleaning potentially corrupted build artifacts (prevents WSL crashes)..."
    
    # Step 1: Clean corrupt dep-graph.bin files (symptom of WSL crashes)
    # These are automatically regenerated by cargo, so safe to delete
    if [ -d "target/debug/incremental" ] || [ -d "target/release/incremental" ]; then
        echo "   Removing corrupt dep-graph.bin files..."
        find target/debug/incremental target/release/incremental -name "dep-graph.bin" -type f -delete 2>/dev/null || true
        # Remove empty incremental directories to prevent stale artifacts
        find target/debug/incremental target/release/incremental -type d -empty -delete 2>/dev/null || true
    fi
    
    # Step 2: Clean potentially corrupted AWS SDK artifacts
    # These can cause "Archive member size is too large" and type inference errors
    if [ -d "target/debug/deps" ] || [ -d "target/release/deps" ]; then
        echo "   Removing potentially corrupted AWS SDK artifacts..."
        find target/debug/deps target/release/deps -name "*aws_sdk_*" -type f -delete 2>/dev/null || true
        find target/debug/incremental target/release/incremental -name "*aws_sdk_*" -type f -delete 2>/dev/null || true
        # Also clean via cargo for proper cleanup
        cargo clean -p aws-sdk-sesv2 -p aws-sdk-ssm 2>/dev/null || true
    fi
    
    echo "✅ Cleanup complete (environment is clean and resilient to WSL issues)"
    echo ""
fi

# Maximize resource usage: Use all available CPU cores and system linker to prevent linker OOM
# The linker (rust-lld) can run out of memory in WSL, but system linkers (gold/bfd) handle large binaries better
CPU_CORES=$(nproc)
export CARGO_BUILD_JOBS=$CPU_CORES

# Use nextest profile for WSL to prevent resource exhaustion (defined early for all test sections)
NEXTEST_PROFILE=""
if [ "$IS_WSL" = "true" ]; then
    NEXTEST_PROFILE="--profile wsl"
fi

if [ "$IS_WSL" = "true" ]; then
    echo "🔧 WSL detected: Maximizing resource usage..."
    echo "   CPU cores: $CPU_CORES (using all for parallel compilation)"
    
    # Use system linker to prevent linker OOM (allows full CPU usage during compilation)
    # Prefer bfd over deprecated gold, fallback to default ld
    if command -v ld.bfd > /dev/null 2>&1; then
        export RUSTFLAGS="-C link-arg=-fuse-ld=bfd"
        echo "   Linker: bfd (GNU binutils, prevents linker OOM)"
    elif command -v ld > /dev/null 2>&1; then
        export RUSTFLAGS="-C link-arg=-Wl,--no-incremental"
        echo "   Linker: default ld with incremental linking disabled"
    else
        echo "   Linker: default (no custom flags)"
    fi
    echo "   Nextest: using 'wsl' profile (300s timeout, prevents resource exhaustion)"
    echo ""
else
    echo "🚀 Maximizing resource usage: $CPU_CORES CPU cores"
    echo ""
fi

# Check for cargo-nextest (used throughout)
# Note: We do NOT pre-compile test dependencies because:
# 1. Cargo's incremental compilation already handles this automatically
# 2. Pre-compiling with --all-features and 20 parallel jobs causes WSL resource exhaustion
# 3. CI doesn't pre-compile - it just runs tests directly (each test run compiles incrementally)
# 4. Each test run will compile only what's needed, using cached artifacts from previous runs
HAS_NEXTEST=$(check_nextest)

# Run all test scripts in order (matching CI execution order in rust-ci.yml)
# Pass --no-neon to skip branch creation (they'll use the shared DATABASE_URL)
FAILED=0

# 1. Unit tests (no database required) - matches CI test-unit job
# These are fast and can run in parallel - good warm-up for compilation cache
echo "1️⃣  Running unit tests (no database, parallel execution)..."
if ! "$SCRIPT_DIR/test-unit.sh"; then
    echo "❌ Unit tests failed"
    FAILED=1
fi
echo ""

# 2. Non-database integration tests (health, routes) - matches CI step 1
# These don't require database, so they're fast and safe to run in parallel
echo "2️⃣  Running non-database integration tests (health, routes, parallel execution)..."
TIMEOUT_NON_DB=$([ "$IS_WSL" = "true" ] && echo "45" || echo "60")

# Don't use external timeout for nextest - it has built-in timeout handling
# External timeout sends SIGTERM which causes improper cleanup and WSL crashes
if [ "$HAS_NEXTEST" = "true" ]; then
    if ! cargo nextest run $NEXTEST_PROFILE --test integration_health --test integration_routes --locked --all-features --test-threads=2; then
        echo "❌ Non-database integration tests failed"
        FAILED=1
    else
        echo "✅ Non-database integration tests passed"
    fi
else
    # Use external timeout for cargo test (it doesn't have built-in timeout)
    if ! timeout "$TIMEOUT_NON_DB" cargo test --test integration_health --test integration_routes --locked --all-features -- --test-threads=2; then
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 124 ]; then
            echo "❌ Non-database integration tests timed out"
        else
            echo "❌ Non-database integration tests failed"
        fi
        FAILED=1
    else
        echo "✅ Non-database integration tests passed"
    fi
fi
echo ""

# 3. Auth tests - matches CI step 2
# MUST run sequentially (--test-threads=1) to avoid migration table race conditions
echo "3️⃣  Running authentication tests (database required, sequential execution)..."
if ! "$SCRIPT_DIR/test-auth.sh" --no-neon; then
    echo "❌ Authentication tests failed"
    FAILED=1
fi
echo ""

# 4. Publisher CRUD tests - matches CI step 3
# MUST run sequentially (--test-threads=1) to avoid migration table race conditions
echo "4️⃣  Running database & CRUD tests (sequential execution)..."
if ! "$SCRIPT_DIR/test-db.sh" --no-neon; then
    echo "❌ Database tests failed"
    FAILED=1
fi
echo ""

# 5. E2E tests - matches CI step 4
# MUST run sequentially (--test-threads=1) to avoid migration table race conditions
echo "5️⃣  Running E2E tests (sequential execution)..."
if cargo test --test integration_carina_e2e --list 2>/dev/null | grep -q "test.*"; then
    TIMEOUT_E2E=$([ "$IS_WSL" = "true" ] && echo "150" || echo "200")
    if [ "$HAS_NEXTEST" = "true" ]; then
        # Don't use external timeout for nextest - it has built-in timeout handling
        if ! cargo nextest run $NEXTEST_PROFILE --test integration_carina_e2e --locked --all-features --test-threads=1 --run-ignored only; then
            echo "❌ E2E tests failed"
            FAILED=1
        fi
    else
        # Use external timeout for cargo test
        if ! timeout "$TIMEOUT_E2E" cargo test --test integration_carina_e2e --locked --all-features -- --test-threads=1 --ignored; then
            echo "❌ E2E tests failed"
            FAILED=1
        fi
    fi
    # Add cleanup delay to allow resources to be released
    sleep 2
    echo ""
fi

# 6. Database-backed library tests (includes routing) - matches CI step 5
# This runs all --lib tests with --run-ignored only, which includes routing tests
# These are database-backed but marked with #[ignore] to skip in unit test runs
# MUST run sequentially (--test-threads=1) to avoid database connection pool exhaustion
echo "6️⃣  Running database-backed library tests (includes routing, sequential execution)..."
TIMEOUT_LIB=$([ "$IS_WSL" = "true" ] && echo "300" || echo "420")
# CI uses --run-ignored only to run only ignored tests (light tests, heavy skipped in CI)
# Local runs with RUN_HEAVY_TESTS=true will run both ignored and non-ignored
if [ "$HAS_NEXTEST" = "true" ]; then
    # Don't use external timeout for nextest - it has built-in timeout handling
    # External timeout sends SIGTERM which causes improper cleanup and WSL crashes
    if ! cargo nextest run $NEXTEST_PROFILE --lib --locked --all-features --test-threads=1 --run-ignored only; then
        echo "❌ Database-backed library tests failed"
        FAILED=1
    fi
else
    # Use external timeout for cargo test (it doesn't have built-in timeout)
    if ! timeout "$TIMEOUT_LIB" cargo test --lib --locked --all-features -- --test-threads=1 --ignored; then
        echo "❌ Database-backed library tests failed"
        FAILED=1
    fi
fi
# Add cleanup delay to allow resources to be released
sleep 2
echo ""

# 7. Optimization tests - matches CI step 6
# MUST run sequentially (--test-threads=1) to avoid conflicts
echo "7️⃣  Running optimization tests (sequential execution)..."
if ! "$SCRIPT_DIR/test-optimization.sh" --no-neon; then
    echo "❌ Optimization tests failed"
    FAILED=1
fi
echo ""

# 8. Endpoint integration tests - matches CI step 7
# MUST run sequentially (--test-threads=1) to avoid database connection pool exhaustion
echo "8️⃣  Running endpoint integration tests (sequential execution)..."
if cargo test --test integration_leads_endpoint --list 2>/dev/null | grep -q "test.*"; then
    TIMEOUT_ENDPOINT=$([ "$IS_WSL" = "true" ] && echo "90" || echo "120")
    # CI uses --run-ignored only
    if [ "$HAS_NEXTEST" = "true" ]; then
        # Don't use external timeout for nextest - it has built-in timeout handling
        if ! cargo nextest run $NEXTEST_PROFILE --test integration_leads_endpoint --locked --all-features --test-threads=1 --run-ignored only 2>&1 | tee /tmp/leads_endpoint_tests.log; then
            FAILED=1
        fi
        # Check for failures in output even if exit code is 0
        if grep -q "test run failed\|FAILED\|error: test run failed\|Cancelling due to signal\|were not run due to signal" /tmp/leads_endpoint_tests.log; then
            FAILED=1
        fi
    else
        # Use external timeout for cargo test
        if ! timeout "$TIMEOUT_ENDPOINT" cargo test --test integration_leads_endpoint --locked --all-features -- --test-threads=1 --ignored 2>&1 | tee /tmp/leads_endpoint_tests.log; then
            FAILED=1
        fi
        if grep -q "test result: FAILED\|FAILED\|error:" /tmp/leads_endpoint_tests.log; then
            FAILED=1
        fi
    fi
    # Add cleanup delay to allow resources to be released
    sleep 2
    echo ""
fi

# Final verdict - check all test logs for failures
if [ $FAILED -eq 0 ]; then
    # Double-check all test logs for any failures that might have been missed
    if [ -f /tmp/optimization_tests.log ] && grep -q "test run failed\|FAILED\|error: test run failed" /tmp/optimization_tests.log; then
        FAILED=1
    fi
    if [ -f /tmp/leads_endpoint_tests.log ] && grep -q "test run failed\|FAILED\|error: test run failed" /tmp/leads_endpoint_tests.log; then
        FAILED=1
    fi
fi

if [ $FAILED -eq 0 ]; then
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "✅ All tests passed!"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    exit 0
else
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "❌ Some tests failed - check logs above for details"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    exit 1
fi
